### ISSUE TITLE
Fragment does not have an empty public constructor

### ISSUE THREAD

**Issue by ogapants** [DroidKaigi/conference-app-2017#131]
## Overview (Required)
According to the document, the empty public constructor must be explicitly defined in Fragment, but it is not defined in this application.
Do you have any reasons?

## Links
- [Fragment | Android Developers](https://developer.android.com/reference/android/app/Fragment.html)

## Screenshot
none

**Comment by konifar** [comment]
Oh, I didn't know that.
I have no reason 🙇

**Comment by jmatsu** [comment]
I don't think the document says that developers have to `implement` default constructor in every Fragment.
As you know, Java compiler can automatically provide a default constructor for any class without constructors.
So the rule is satisfied if Fragment has no constructors.
Then, the document just wanna say that Fragment must not have constructors without defining a default constructor, I think.

Anyway, it's good for people who don't know this rule to define a default constructor expressly. 😃 
Thanks @ogapants !

**Comment by ogapants** [comment]
@jmatsu Sorry for my misunderstanding... It helps me a lot!
