### ISSUE TITLE
Apply constraint layout to view_session_cell.xml

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2017#139]
## Overview (Required)
Currently, this app doesn't use ConstraintLayout, but there is no reason.
I want to try to use it 😃 

## Links
- https://developer.android.com/reference/android/support/constraint/ConstraintLayout.html

**Comment by chibatching** [comment]
Hi, I can't find `view_session.xml` in the project. Does it means `view_session_cell.xml`?

**Comment by konifar** [comment]
Ah, sorry, right. `view_session_cell.xml` is correct!

**Comment by chibatching** [comment]
Thanks! I'll try it!
