### ISSUE TITLE
Handling anonymous contributors

### ISSUE THREAD

**Issue by shiraji** [DroidKaigi/conference-app-2017#148]
## Overview (Required)
Currently, contributors page only lists non-anonymous contributors. 

Anonymous contributors are the user who contributes this project but the commit author doesn't connect with GitHub account.
https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/

I don't think we can just ignore those contributors.

I think these 2 commits are not counted as contributions.
https://github.com/DroidKaigi/conference-app-2017/pull/115/commits

The things I concern about is the api only return values like the following:

```
  {
    "email": "EMAIL",
    "name": "NAME",
    "type": "Anonymous",
    "contributions": 2
  },
```

(email/name is actual value)

There is no icon to display and no url to jump...but still there is name we can list on the contributors page.

Do you think we should list anonymous contributors?

## Links
Parameter for getting anonymous contributors
https://developer.github.com/v3/repos/#parameters-4

## Screenshot
N/A

**Comment by shiraji** [comment]
OK, I will work on this. if this is not sufficient, you guys just close the PR.

**Comment by konifar** [comment]
Sounds great! 👍
