### ISSUE TITLE
Disable or split repository link on contributor item?...

### ISSUE THREAD

**Issue by sys1yagi** [DroidKaigi/conference-app-2017#169]
## Overview (Required)

I intended to open a contributor list, but it opened the repository and it got confused... :astonished:
Would you like to disable or split the repository link on contributor items?

## Links

None

## Screenshot

such as 

![c](https://cloud.githubusercontent.com/assets/749051/22694075/194ee4b8-ed89-11e6-855f-6958c1bb396f.gif)

**Comment by konifar** [comment]
Thanks for report!

How about remove the link from the description and add the link menu icon to the contributor page?

**Comment by sys1yagi** [comment]
>How about remove the link from the description and add the link menu icon to the contributor page?

sounds good!

**Comment by noboru-i** [comment]
I try to change that.
https://github.com/DroidKaigi/conference-app-2017/pull/295

Is that PR same as you want..?

**Comment by konifar** [comment]
@noboru-i Yep, thanks!
