### ISSUE TITLE
Cached sessions should depend on language

### ISSUE THREAD

**Issue by amay077** [DroidKaigi/conference-app-2017#211]
## Overview (Required)

``SessionsRepository.findAll(languageId)`` seems returns independent of ``languageId`` when has cache. 
In device language is English, but if cached sessions are Japanese then returns Japanese sessions.

Do you have any plan or design? 

* Yes, we should implement in some way
* No need implementation because ``cachedSessions`` is memory cache and we don't have a plan to "In-App language changing"
* Enough for us. If languageId changed then just call ``SessionsRepository.setIdDirty(true)``
* Others

## Details

```java
// SessionsRepository.java
@Override
public Single<List<Session>> findAll(String languageId) {
    if (hasCacheSessions()) {
        return Single.create(emitter -> {
            try {
                emitter.onSuccess(new ArrayList<>(cachedSessions.values()));
            } catch (Exception e) {
                emitter.onError(e);
            }
        });
    }

    if (isDirty) {
        return findAllFromRemote(languageId);
    } else {
        return findAllFromLocal(languageId);
    }
}
```

## Links

* https://github.com/DroidKaigi/conference-app-2017/blob/master/app/src/main/java/io/github/droidkaigi/confsched2017/repository/sessions/SessionsRepository.java#L37
* https://github.com/DroidKaigi/conference-app-2017/blob/master/app/src/main/java/io/github/droidkaigi/confsched2017/repository/sessions/MySessionsRepository.java#L32

**Comment by k-kagurazaka** [comment]
@konifar 
I found that both "ja" and "en" resources (sessions.json) return the same file now.
Do you have a plan for translating the resource?
If not, this issue is no problem, the cache can be used for all language:sunglasses:

**Comment by konifar** [comment]
> Do you have a plan for translating the resource?

Good point. We don't have any plan to translate now.
So as you said, it's no problem.

**Comment by amay077** [comment]
Ok, I closed this.
If we want to English sessions.json, somebody will open new issue.
Thanks! 👍

**Comment by konifar** [comment]
Thanks for report!
