### ISSUE TITLE
After party cell col span should be 6

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2017#219]
Assigned to @shiraji 

## Overview (Required)
Currently, after party cell is 1.
But it should be 6 like welcome talk.

<img width="300" alt="screenshot_jpg__1080x1920_" src="https://cloud.githubusercontent.com/assets/1269214/22742614/b829ccf2-ee5a-11e6-914f-27c697ee3c22.png">

## Links
- https://github.com/DroidKaigi/conference-app-2017/blob/master/app/src/main/java/io/github/droidkaigi/confsched2017/viewmodel/SessionViewModel.java#L115

**Comment by shiraji** [comment]
Here is the value from sessions.json

```
{"id":72,"title":"アフターパーティ / AfterParty","date":"2017/03/10","start_time":"18:30","end_time":"20:30","stime":"2017/03/10 18:30:00","etime":"2017/03/10 20:30:00","duration_min":120,"type":"dinner","desc":"アフターパーティではお寿司をはじめ、美味しい料理とドリンクを用意しています。みんなでワイワイ楽しみませんか？\nhttps://droidkaigi.connpass.com/event/43942/ で参加を受け付けています。\n\n楽しんじゃいましょう、気楽に！"}
```

The interesting part is `"type":"dinner"`. So the question is "is data correct"?

If there is type "dinner", then it seems [enum](https://github.com/DroidKaigi/conference-app-2017/blob/master/app/src/main/java/io/github/droidkaigi/confsched2017/model/Session.java#L88) missing value "dinner". Is there any other type missing?

**Comment by konifar** [comment]
> So the question is "is data correct"?

It's correct. We have to add new enum type `DINNER`.

**Comment by shiraji** [comment]
OK. I will work on this issue.

**Comment by shiraji** [comment]
Is this what you want? It's same colspan with welcome speech but not 6.

![2017-02-09 1 43 47](https://cloud.githubusercontent.com/assets/3675458/22747047/3e67fc18-ee69-11e6-9b35-5aac4b0169b9.png)

**Comment by konifar** [comment]
Thanks!
No, I think the colspan should be 6.

**Comment by shiraji** [comment]
Then, can I fix welcome speech's colspan, too?

![2017-02-09 1 48 40](https://cloud.githubusercontent.com/assets/3675458/22747252/edee2fb8-ee69-11e6-9188-72930ec3ab4e.png)

**Comment by konifar** [comment]
No, welcome talk session is held in room 1~3, so colspan=3 is correct 😃
