### ISSUE TITLE
FAB margin is missing on pre-lollipop

### ISSUE THREAD

**Issue by ogapants** [DroidKaigi/conference-app-2017#220]
## Overview (Required)
It is due to the small value of `FabMargin` on `styles_compat.xml` for pre-lollipop.
What is it necessary for?

## Links
none

## Screenshot
<img src="https://cloud.githubusercontent.com/assets/11440952/22742746/3ee8ef66-ee5b-11e6-983f-f49db440f194.png" width="300" />

**Comment by konifar** [comment]
On `support:design:22.2.0`, this workaround is necessary.
http://qiita.com/konifar/items/7207ac5348b157d48362

But maybe it's fixed on the latest lib version 🤔
