### ISSUE TITLE
Close search result list when background cover is tapped

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2017#224]
## Overview (Required)
- Currently, SearchActivity is finished when the user tap background cover.
- But I think the search results list should be closed when the user tap background cover.

<img width="300" alt="asus_z00ad" src="https://cloud.githubusercontent.com/assets/1269214/22744399/9e83bd16-ee60-11e6-85a1-ec38d82b416f.png">

**Comment by koooge** [comment]
This seems to occurr when tapped back key.

**Comment by konifar** [comment]
@koooge Right! I'll create another issue 📝 Thanks!
