### ISSUE TITLE
Replace to ConstraintLayout to view_search_result.xml

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2017#226]
## Overview (Required)
Now almost layout is written by LinearLayout and RelativeLayout.
But I want to try to use `ConstraintLayout` more.

## Links
- https://github.com/DroidKaigi/conference-app-2017/pull/157

**Comment by ryugoo** [comment]
@konifar 
Hi! I implemented two patterns layout.
Which of these is better than these? :)

1. **Simple**<br>Simple replace to ConstraintLayout that is looks like same.
2. **Modify**<br>Add right constraint to caption text.

Original | Simple | Modify
:--: | :--: | :--:
<img src="https://cloud.githubusercontent.com/assets/1000715/22861476/fc4299aa-f15c-11e6-8699-18a72ae5bfb7.png" width="200" /> | <img src="https://cloud.githubusercontent.com/assets/1000715/22861477/01fccf50-f15d-11e6-945f-833a83470a51.png" width="200" /> | <img src="https://cloud.githubusercontent.com/assets/1000715/22861478/04c54dfc-f15d-11e6-956e-564ba4beaad9.png" width="200" />

**Comment by konifar** [comment]
@ryugoo Hi, thanks for tackling!
Original layout is corrupted. `2. Modify` looks better 😄
