### ISSUE TITLE
Check sessions in sessions page

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2017#231]
## Overview (Required)
Currently, the user can check/uncheck sessions from SessionDetail page.
When the user long tap the session item in Sessions page, it's better to check/uncheck the session.
It's just my idea.

<img width="300" alt="screenshot_jpg__1080x1920_" src="https://cloud.githubusercontent.com/assets/1269214/22745926/7fe120a6-ee65-11e6-8b22-35319971e552.png">

**Comment by shiraji** [comment]
I'm gonna take this one, if no one work on this.

**Comment by konifar** [comment]
Maybe no one is working on. Please go ahead!
