### ISSUE TITLE
Add check mark icon should be shown in SearchResult

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2017#232]
## Overview (Required)
<img width="300" alt="screenshot_jpg__1080x1920_" src="https://cloud.githubusercontent.com/assets/1269214/22746219/6ca424d8-ee66-11e6-9fae-2ccaf89abe08.png">

`ic_check_circle_24_vector.xml`

**Comment by kwmt** [comment]
Hi, I have a question.
When you go to a session detail screen from search result and then go back to search result after save the session detail as mysession, do you want to reload  search result screen  to see check mark icon?

**Comment by konifar** [comment]
@kwmt 
> do you want to reload search result screen to see check mark icon?

Yes, exactly.

**Comment by kwmt** [comment]
@konifar Thanks for your reply. 
OK, I got it 😄

**Comment by kwmt** [comment]
@konifar  Sorry, I found one question 😅 
Does the check mark icon need to place just right side of session title?

Or does your image have an image like the image below?

<img src="https://cloud.githubusercontent.com/assets/1450486/22813089/3ac4d576-ef8c-11e6-8d82-7f8db5505706.png" width="300" />

**Comment by konifar** [comment]
> Does the check mark icon need to place just right side of session title?

Originally, I thought as you said.
But I think it's okay to put the check icon to the left side of session title 💭 
Can you try it? 🙇

**Comment by kaelaela** [comment]
@kwmt 
Sorry, I've tried this issue from yesterday. 🤣 
But, this implementation can't reload results.
Could you help me?

**Comment by kwmt** [comment]
@konifar Thank you for quickly reply!
@kaelaela No problem! Your code is simpler than mine. 😄
I did not implement it yet. So I think it might be faster for you to implement it. 😅 
But I'll try it.
