### ISSUE TITLE
Add language settings

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2017#233]
## Overview (Required)
Add language (`ja` and `en`) settings to settings page.

On DroidKaigi 2016 app, it was implemented.

<img width="300" alt="screenshot_jpg__1080x1920_" src="https://cloud.githubusercontent.com/assets/1269214/22746467/18127676-ee67-11e6-8031-a40907c290d4.png">

## Links
- https://github.com/konifar/droidkaigi2016/blob/master/app/src/main/java/io/github/droidkaigi/confsched/fragment/SettingsFragment.java#L82

**Comment by Kuchinashi** [comment]
I want to join!

**Comment by Pluu** [comment]
@Kuchinashi sorry. I worked on the same issue. but, My PR `Conflicting` Status
