### ISSUE TITLE
Prevent user's continuous hitting while the Fragment transaction is working.

### ISSUE THREAD

**Issue by neonankiti** [DroidKaigi/conference-app-2017#235]
## Overview (Required)
-  When I hit the BottomNavigationView Item continuously at the same time, it would often cause this below. (screenshot)

- execute the transaction at once before starting the new transactions. 

## Links
- https://developer.android.com/reference/android/app/FragmentManager.html
- http://qiita.com/tomoima525/items/d10fda955a97c265f338

## Screenshot
<img src="https://cloud.githubusercontent.com/assets/6552589/22745578/700f50f4-ee64-11e6-9f33-6befcc7bcc3e.png" width="300" />

**Comment by konifar** [comment]
Thanks for your report!

> execute the transaction at once before starting the new transactions.

Make sense.
