### ISSUE TITLE
Detect memory leaks of com.tomoima.debot.Debot in SessionDetailActivity

### ISSUE THREAD

**Issue by amay077** [DroidKaigi/conference-app-2017#246]
Assigned to @tomoima525

## Overview (Required)

I'm testing app installed by DeployGate ＃123.
LeakCanary caught memory leaks in SessionDetailActivity.

### Steps for REPRO

1. Launch app and shown sessions page
2. Tap to any session and open session detail page
3. Back to session page with tap to ← button
4. Wait a some minutes
5. LeakCanary reports leaks

I think this issue is related to [PR 207](https://github.com/DroidKaigi/conference-app-2017/pull/207).
@tomoima525, Could you help us?

## Links
- https://github.com/DroidKaigi/conference-app-2017/pull/207

## Screenshot
<img src="https://cloud.githubusercontent.com/assets/401369/22770679/8eb87f78-eed5-11e6-9824-a0b09db2f450.gif" width="300" />

## Dump

* [dump.txt](https://github.com/DroidKaigi/conference-app-2017/files/762691/dump.txt)

**Comment by tomoima525** [comment]
got it, let me take a look

**Comment by konifar** [comment]
@tomoima525 I assigned you, but PR has been sent...! Too fast...
https://github.com/DroidKaigi/conference-app-2017/pull/248

**Comment by ytRino** [comment]
oops sorry i didnt noticed for comment while working on this :bow:

**Comment by konifar** [comment]
@ytRino Never mind! Thank you for super quick fix! ⚡️

**Comment by tomoima525** [comment]
Oh my god, you are awesome !! 👍  @ytRino
