### ISSUE TITLE
Add link to T-Shirt EC page

### ISSUE THREAD

**Issue by KeithYokoma** [DroidKaigi/conference-app-2017#247]
## Overview (Required)
- Put a link to T-Shirt EC page somewhere in the app

## Links
- http://ec-mail.freegufo.com/items/5215140
-- The page is optimized for smartphone :)

**Comment by konifar** [comment]
Are there any other goods? If so, how about adding `Goods` row to Settings page?

**Comment by jmatsu** [comment]
NOTE: The ec page is available until 3/1 (Wed) 18:00 JST

**Comment by KeithYokoma** [comment]
Oops!

**Comment by konifar** [comment]
Sorry, let me close this 🙇 
Thanks for interesting idea!
