### ISSUE TITLE
Enable lint check for CI

### ISSUE THREAD

**Issue by shiraji** [DroidKaigi/conference-app-2017#266]
## Overview (Required)
Currently lint check is ignored because of https://github.com/DroidKaigi/conference-app-2017/blob/master/app/build.gradle#L112

I think it is time to enable this check. What do you guys think?

## TODO

- [ ] Fix all error/fatal lint checks
- [ ] Delete `abortOnError false`

## Links
-

## Screenshot
<img src="" width="300" />

**Comment by KeithYokoma** [comment]
Currently we have 24 issues in total (master), and some of them can be ignored/suppressed and others should be corrected.

I think it's okay to enable the check, but I want to have some notification strategy for developers that the build failed for a new lint check failure in the future. Currently build log just says lint found xxx issues but no explanation, although we have a html report in artifact directory on CircleCI so we can check the result with it.

**Comment by shiraji** [comment]
Maybe we can use these options

```groovy
        // if true, generate a text report of issues (false by default)
        textReport true
        // location to write the output; can be a file or 'stdout'
        textOutput 'stdout'
```

**Comment by yshrsmz** [comment]
Hi, I'd like to propose [reviewdog](https://github.com/haya14busa/reviewdog) as a lint notifier.

This tool can post review comments to PR, without any complex setup.

## PROs

- easy to setup(just one single binary!)
- can interact with any lint tool(Android Lint, CheckStyle, PMD...)

## CON

- need to expose GitHub access token(and other environmental variables) to build PRs from extenal repo
  - https://github.com/haya14busa/reviewdog#working-with-github-and-ci-services
  - https://circleci.com/docs/fork-pr-builds/#security-implications-of-running-builds-for-pull-requests-from-forks

if CON is acceptable, I can create a PR to setup reviewdog.

**Comment by konifar** [comment]
:eyes:

**Comment by konifar** [comment]
@yshrsmz Thanks for interesting proposal! And sorry for late comment 🙇 
I agree to introduce reviewdog.
Can you try to create PR?

**Comment by yshrsmz** [comment]
@konifar Thanks for your response. Ok, I'll make a PR.

There are few things I'd like you to do to setup reviewdog.

- Get someone's(preferably a bot acoount) GitHub personal access token with `public_repo` scope. reviewdog will make a comment as this account.
  - https://github.com/haya14busa/reviewdog#working-with-github-and-ci-services
- Set that access token to Circle CI's environmental variable as `REVIEWDOG_GITHUB_API_TOKEN`
  - https://github.com/haya14busa/reviewdog#working-with-github-and-ci-services
- Enable `Pass secrets to builds from forked pull requests.` in Circle CI's settings page.(`Settings > Build Settings > Advanced Settings`)
  - https://circleci.com/docs/fork-pr-builds/#security-implications-of-running-builds-for-pull-requests-from-forks

**Comment by konifar** [comment]
Let me close this.
