### ISSUE TITLE
Adjust sponsors page layout

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2017#279]
## Links
- https://github.com/DroidKaigi/conference-app-2017/pull/172#discussion_r100490908

**Comment by shiraji** [comment]
I'm not sure does this look good for you? 

<img src="https://cloud.githubusercontent.com/assets/3675458/22838444/8978988e-f008-11e6-8cc4-9a3465247578.png" width="300" /><img src="https://cloud.githubusercontent.com/assets/3675458/22838443/8977b70c-f008-11e6-9422-ff72ce7b3af5.png" width="300" />

**Comment by konifar** [comment]
Thanks for quick fix!!
I want you to fix some points more :bowing_man:
Let me comment tomorrow!

**Comment by shiraji** [comment]
Sure! Then I will take care this issue.

**Comment by konifar** [comment]
@shiraji Can you change them? 🙇 
<img width="300" alt="8978988e-f008-11e6-8cc4-9a3465247578_png__670x1114_" src="https://cloud.githubusercontent.com/assets/1269214/22850618/04718784-f050-11e6-8680-36336a159a33.png">

**Comment by konifar** [comment]
Thanks! @shiraji
