### ISSUE TITLE
All my sessions clears when the application restart.

### ISSUE THREAD

**Issue by yatatsu** [DroidKaigi/conference-app-2017#282]
Assigned to @yatatsu 

## Overview (Required)
- MySession clear when sessions update (e.g. app restart).
- Session is once deleted all, and inserted.
- MySession has association to Session, and it was also deleted too.

## How to Reproduce
- Start the app and check some sessions.
- Kill the app and restart it.
- Sessions page looks good because it takes before sessions update from remote.
- But in session detail page, all sessions are not checked.

## Links
- https://speakerdeck.com/lvla/ormahamaripointo-star-v2-dot-5-2
- https://github.com/gfx/Android-Orma/issues/294

## Screenshot
- None

**Comment by konifar** [comment]
Thanks for report! It's critical... 😭

**Comment by gfx** [comment]
👀
