### ISSUE TITLE
Create cool splash screen

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2017#29]
Assigned to @roana0229

## Overview (Required)
- I want the splash screen with droidkaigi2017 droid icon and animated background view.
- Like web page header https://droidkaigi.github.io/2017/en/

## Screenshot
<img width="1272" alt="droidkaigi_2017" src="https://cloud.githubusercontent.com/assets/1269214/21993582/ea0c0df6-dc5e-11e6-8275-1ea8dabc1be8.png">

**Comment by roana0229** [comment]
Thank you! I fun making this. 😃

**Comment by konifar** [comment]
Thanks for contribution! @roana0229
