### ISSUE TITLE
"Welcome talk talk" is shown in Toolbar

### ISSUE THREAD

**Issue by YusukeIwaki** [DroidKaigi/conference-app-2017#336]
## Overview (Required)
Toolbar shows thw word "talk" twice unexpectedly, during collapsing.

I don't know if this bug is caused by the bug of support libs or by some kind of implementation :sweat_smile:

Actually this bug is really trivial, and no need to fix soon. However it would be better for us to share the issue and the workaround (if it exists). :) 

## Screenshot

<img src="https://cloud.githubusercontent.com/assets/11763113/22921153/d3ffe9a4-f2db-11e6-8ef1-ab6efb768fc8.png" width=300/>

**Comment by konifar** [comment]
:eyes:

**Comment by konifar** [comment]
Thanks for report!
Actually we use [multiline-collapsingtoolbar](https://github.com/opacapp/multiline-collapsingtoolbar) which extends support lib CollapsingToolbar to show multiline text.

This seems the library's spec, not bug 🤔 But I guess black text is wrong.

**Comment by hironytic** [comment]
I think [this issue](https://github.com/opacapp/multiline-collapsingtoolbar/issues/27) is related.

We can avoid this problem by simply deleting the shadow in `SessionDetailExpandedToolbarTitle` style, but the appearance becomes worse. :worried:

**Comment by konifar** [comment]
@hironytic Thanks!
I guess it might be better to remove shadow and put black alpha color on the background image 💭
