### ISSUE TITLE
Up button of session detail view always navigate to the MainActivity

### ISSUE THREAD

**Issue by k-kagurazaka** [DroidKaigi/conference-app-2017#352]
## Overview (Required)
- Title says almost all things. This behavior confuse users that open session detail view via my session view.

## Links
https://github.com/DroidKaigi/conference-app-2017/blob/770be936d1fa4ff1ae09c45e7c9dd8b1c23c715a/app/src/main/java/io/github/droidkaigi/confsched2017/view/activity/SessionDetailActivity.java#L44

**Comment by konifar** [comment]
Thanks @kobakei !!

**Comment by kobakei** [comment]
You're welcome 💪
