### ISSUE TITLE
Why use "Iterator" for Adapter?

### ISSUE THREAD

**Issue by eneim** [DroidKaigi/conference-app-2017#358]
## Overview (Required)

I see there is an abstract "ArrayRecyclerAdapter" class which implements the Iterator interface. My wonder is why it is need?

In the case we really want the ability to iterate over the list, [this line](https://github.com/DroidKaigi/conference-app-2017/blob/master/app/src/main/java/io/github/droidkaigi/confsched2017/view/customview/ArrayRecyclerAdapter.java#L74) makes me feel unsafe. 

Once you iterator over the ***list*** member, its content can be changed (calling **Iterator#remove** for example), and this changed may not be properly observed (i.e one may not call notifyChange properly due to the lack of documentation). The next question is should we allow the list to be changed by being an Iterator (rather than by normal add/addAll method)? In that case, please document out this usage by a simple comment.

**Comment by eneim** [comment]
@konifar Just a bit unclear, but it is not a fatal issue. The point is: why we need it to be iterator :p. Nothing special here. (A miss-use of it can be trouble, but it is rare).

**Comment by konifar** [comment]
Sorry, I don't remember why I implemented `iterator` 🙇 
But as you said, it looks unnecessary now.

**Comment by konifar** [comment]
This is improved by @shiraji ! Thanks!
