### ISSUE TITLE
New object allocation in onDraw

### ISSUE THREAD

**Issue by eneim** [DroidKaigi/conference-app-2017#365]
I wonder if [this line](https://github.com/DroidKaigi/conference-app-2017/blob/master/app/src/main/java/io/github/droidkaigi/confsched2017/view/customview/ParticlesAnimationView.java#L63) will allocate new Stream instances on every call. So it is something we don't want to do in onDraw. (This view is now used only in Plash screen so performance is not a big issue).

**Comment by konifar** [comment]
Maybe there is no reason 💭

**Comment by konifar** [comment]
@kitwtnb 
Thanks! #366

**Comment by eneim** [comment]
@konifar Just made a comment on the PR :D.
