### ISSUE TITLE
User is able to return to Splash screen when tapping on back button immediately after Sessions screen is launched

### ISSUE THREAD

**Issue by miga9** [DroidKaigi/conference-app-2017#377]
## Overview (Required)
- User is able to return to Splash screen when tapping on back button immediately after Sessions screen is launched. 

It does not happen after a few seconds are elapsed after Sessions screen is launched. App closes fine after tapping on back button again.

## Reproduction steps
- Launch the app.
- Splash screen loads.
- Sessions screen is opened. Tap on back button within a couple seconds.
- Observe that user is able to return to Splash screen.

## Links
- N/A

## Screenshot
<img src="" width="300" />

**Comment by konifar** [comment]
Thanks shiraji!
