### ISSUE TITLE
Create Session Feedback page

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2017#74]
## Overview (Required)
Maybe it's good to use GoogleForm API.
https://github.com/konifar/droidkaigi2016/blob/master/app/src/main/java/io/github/droidkaigi/confsched/api/DroidKaigiClient.java#L48

## Links
- https://github.com/konifar/droidkaigi2016/blob/master/app/src/main/java/io/github/droidkaigi/confsched/activity/SessionFeedbackActivity.java

**Comment by shiraji** [comment]
Still opened?

**Comment by operando** [comment]
Session feedback URL :muscle: 
https://docs.google.com/a/mercari.com/forms/d/e/1FAIpQLSf5NydpYm48GXqlKqbG3e0dna3bw5HJ4GUg8W1Yfe4znTWH_g/viewform

**Comment by konifar** [comment]
Will do!!!
