### ISSUE TITLE
Create sponsors page

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2017#76]
## Overview (Required)
- There are many sponsors for DroidKaigi.

## Links
- https://droidkaigi.github.io/2017/#sponsors

**Comment by eyedol** [comment]
@konifar  I'm interested in working on this. Anyway you could make the paper mock ready? or where can I see it?

**Comment by konifar** [comment]
@eyedol Thanks! Sure! I'll put the paper mock here tonight.

**Comment by konifar** [comment]
<img width="811" alt="droidkaigi_2017" src="https://cloud.githubusercontent.com/assets/1269214/22655180/ae4e25b8-ecd2-11e6-8d52-a652430054f4.png">

All sponsors info is here https://droidkaigi.github.io/2017/en/#sponsors

Now we don't have API to get sponsors. So we have to create local json data like this.

```json
[
{
  category: "Platinum sponsors",
  sponsors: [
    {
      image_url: "http://~~.png",
      site_url: "http://~~"
    },
    ...
  ]
},
...
]
```

**Comment by eyedol** [comment]
@konifar Thanks for the design doc. Looks good. Expect a `PR` soon.
