### ISSUE TITLE
Create questionnaire page

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2017#77]
## Overview (Required)
- Create Quesionnaire page.
- Or show web quesionnaire page.

**Comment by konifar** [comment]
Probably we'll use GoogleForm API as same as SessionFeedback page.

**Comment by shiraji** [comment]
Can I work on this? Could you elaborate?

**Comment by konifar** [comment]
@shiraji Sorry, I didn't notice your comment 🙇 
In fact, we haven't prepared questionnaire yet. So let us handle this issue.
That's why I didn't add `welcomecontributor` label.

**Comment by hkurokawa** [comment]
@shiraji Hi, we have [a Google form](https://docs.google.com/forms/d/1SNBvJernnyBwglNentXxpdSUkWI9U6umWdDs4Na8OIU/edit) for the questionnaire and I am wondering whether we could implement the questionnaire page just like the session feedback page (https://github.com/DroidKaigi/conference-app-2017/pull/134). Do you have time to work on this?

I believe the minimum requirement is adding a link to the Google form somewhere. Let me know your thoughts.

**Comment by shiraji** [comment]
Sure. But since we only have less than 2 weeks to go, I will first add link to the Google form on `InformationFragment`. And then, after that create an Activity for questionnaire page. What do you think @hkurokawa ?

**Comment by konifar** [comment]
@shiraji Agree with you. Thanks and sorry for asking too late :bow:
We will release at 3/4 (Sat) at first. There is not much time, but don't work too hard, take your time.

**Comment by shiraji** [comment]
@konifar No worry. I don't work too hard! 😆 

I will send first PR within one or two days. It's just adding one line for adding link, i guess.

**Comment by konifar** [comment]
Thanks!

**Comment by hkurokawa** [comment]
Agreed. Sorry for much delay in my handling this issue 🙇  💦

**Comment by shiraji** [comment]
One question about Google form. Is there a way to get POST request fields? (e.g. [entry.684428626](https://github.com/DroidKaigi/conference-app-2017/blob/bf541ea1f0965cc98f73b7fad949a524404d690b/app/src/main/java/io/github/droidkaigi/confsched2017/api/service/GoogleFormService.java#L14) or [droidkaigi2016](https://github.com/konifar/droidkaigi2016/blob/6e264b8ef2ba47484f3bd1cbd7d79140086545e1/app/src/main/java/io/github/droidkaigi/confsched/api/DroidKaigiClient.java#L112-L118)) 

Get all of them from HTML source?

**Comment by konifar** [comment]
Hmm, sorry I don't know...
@hkurokawa Do you remember?

**Comment by hkurokawa** [comment]
IIRC, I got the field names from the HTML source code of the Google form page. Awkward but it worked.

**Comment by konifar** [comment]
@shiraji FYI, `fragment_session_feedback.xml` may help you.

**Comment by shiraji** [comment]
Yea. I copy and paste most of code from session feedback pages for start. Thanks.

I think I need to send questionnaire responses multiple time for testing purposes. I'm sorry if the responses are annoying. I hope you can delete the test data before droidkaig.

**Comment by konifar** [comment]
💪
