### ISSUE TITLE
Create licence page

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2017#79]
Assigned to @chibatching

## Overview (Required)
- Create local html and read it.
- Or is it better to use https://github.com/cookpad/license-tools-plugin ?

## Links
https://github.com/konifar/droidkaigi2016/blob/master/app/src/main/assets/license.html
- https://github.com/cookpad/license-tools-plugin

## Screenshot
<img src="" width="300" />

**Comment by Yuiki** [comment]
I am now using https://github.com/cookpad/license-tools-plugin to create a license page.
I forgot to turn it into In Progress.
I'm sorry.
