### ISSUE TITLE
Create development page

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2017#80]
## Overview (Required)
- From information page.
- Debug info and debug menu on the page.

**Comment by shiraji** [comment]
What kind of debug info do you want to show there?

**Comment by konifar** [comment]
@shiraji Sorry, I have no concrete plan now 🤔

**Comment by shiraji** [comment]
How about clearing cache?

**Comment by KeithYokoma** [comment]
Like [u2020](github.com/JakeWharton/u2020), I can add debug setting drawer and easily switch retrofit behaviour for debugging purpose(e.g. change error rate, network delay).

**Comment by tomoima525** [comment]
Hi guys, I just made a PR to add a debug menu on the app, you might want to take a look.
However, it's not following the requirement listed here. Probably I should add Debug info and debug menu on the information page.
