### ISSUE TITLE
Change ic_launcher

### ISSUE THREAD

**Issue by konifar** [DroidKaigi/conference-app-2017#83]
## Overview (Required)
Current icon is temporary I created before.

**Comment by ShogoMizumoto** [comment]
I’ll give it a try.

**Comment by konifar** [comment]
Cool! 🆒 Thank you so much!
I want to change to the icon @wariemon created.
http://wariemon.com/post/151555749659/droidkaigi2017

**Comment by ShogoMizumoto** [comment]
OK, I tried making icon. Is it nice?

<img width="413" alt="screen shot 2017-02-16 at 2 47 23" src="https://cloud.githubusercontent.com/assets/6926816/22987520/61d7baf6-f3f2-11e6-90e3-5222ff069f05.png">

**Comment by konifar** [comment]
Looks good! Go ahead 👍
